sudo: false

language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
  - composer self-update
  - cp composer.json.dist composer.json

install:
  - composer require xoops/base-requires:dev-master
  - composer update

before_script:
  - mysql -e 'create database xoops_test;'
  - php console/console.php ci-bootstrap
  - php console/console.php ci-install
  - php console/console.php install-module avatars
  - php console/console.php install-module page

script:
  - xoops_lib/vendor/bin/phpunit
  - wget https://github.com/diff-sniffer/git/releases/download/0.1.0/git-phpcs.phar
  - php git-phpcs.phar origin/$TRAVIS_BRANCH...$TRAVIS_PULL_REQUEST_SHA

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
