sudo: false

language: php

php:
  - 7.1
  - 7.2
  - 7.3
#  - 7.4snapshot

#matrix:
#  allow_failures:
#    - php: 7.4snapshot

before_install:
  - composer self-update

install:
  - composer --working-dir=htdocs/xoops_lib/ install
  - wget https://github.com/diff-sniffer/git/releases/download/0.2.0/git-phpcs.phar

before_script:
  - mysql -e 'create database xoops_test;'
  - php console/console.php ci-bootstrap
  - php console/console.php ci-install
  - php console/console.php install-module avatars
  - php console/console.php install-module userrank
  - php console/console.php install-module page

script:
  - htdocs/xoops_lib/vendor/bin/phpunit
  - php git-phpcs.phar $TRAVIS_COMMIT_RANGE

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.4snapshot" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.4snapshot" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
